language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5
install: pip install -U -r requirements.txt
before_script:
  - phantomjs --version  # angular works with 2.0+ and travis only offers 1.9.8
  - npm install phantomjs-prebuilt
  - export PHANTOMJS_PATH=`pwd`/node_modules/.bin/phantomjs
  - $PHANTOMJS_PATH --version
  - pip install python-coveralls selenium
  - "export DJANGO_SETTINGS_MODULE=idbase_site.settings"
  - python manage.py migrate
script:
  - py.test --pep8 --cov idbase
  - py.test tests/functional_tests.py
after_success:
  - coveralls
