language: python
python:
  - 2.7
  - 3.5
install: pip install -r requirements.txt
before_script:
  - pip install python-coveralls selenium
  # the following two tasks are only needed to run functional_tests.
  - python manage.py migrate
  - python manage.py runserver &
script:
  - py.test --pep8 --cov idbase
  - py.test tests/functional_tests.py
  - coveralls
